create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  category text not null,
  category_slug text not null,
  price_brl numeric(12,2) not null check (price_brl > 0),
  wholesale_price_brl numeric(12,2),
  wholesale_min_qty integer,
  stock integer not null default 0 check (stock >= 0),
  weight_range text not null check (weight_range in ('100g-1kg','1kg-3kg','3kg-5kg','5kg-10kg','10kg-15kg','15kg-20kg')),
  image text not null,
  tag text not null,
  description text not null,
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  public_id text not null unique,
  customer_name text not null,
  customer_email text not null,
  region text not null,
  status text not null default 'pending' check (status in ('pending','paid','preparing','shipped','cancelled')),
  total_brl numeric(12,2) not null default 0,
  paid_at timestamptz,
  inventory_applied boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  quantity integer not null check (quantity > 0),
  unit_price_brl numeric(12,2) not null check (unit_price_brl >= 0)
);

create index if not exists idx_products_slug on public.products(slug);
create index if not exists idx_orders_public_id on public.orders(public_id);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_order_items_product_id on public.order_items(product_id);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy if not exists "public can read active products"
on public.products
for select
using (active = true);

create policy if not exists "authenticated users can read own orders"
on public.orders
for select
using (auth.uid() is not null and customer_email = auth.email());

create policy if not exists "authenticated users can read own order items"
on public.order_items
for select
using (
  exists (
    select 1
    from public.orders
    where orders.id = order_items.order_id
      and auth.uid() is not null
      and orders.customer_email = auth.email()
  )
);
